name: Release

on:
  push:
    tags:
      - v*

jobs:

  docker_release:  
    # Docker Push Doc: https://docs.docker.com/engine/reference/commandline/push
    # Get Git Tag: https://github.com/orgs/community/discussions/26686
    name: Docker Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mail-bot:latest ${{ secrets.DOCKERHUB_USERNAME }}/mail-bot:${{ github.ref_name }}
    
  github_release:  
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Changelog Generator
        uses: Bullrich/generate-release-changelog@master
        id: generator
        env:
          REPO: ${{ github.repository }}
      - name: Create Github Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ${{ steps.generator.outputs.changelog }}
          draft: false
          prerelease: false
  
